name = "pmg-starter"
compatibility_date = "2024-10-01"

# Enable the Node compatibility flag
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

main = "dist/_worker.js"

[vars]
ZEPTO_TOKEN = "test-token"
RECIPIENT_EMAIL = "test@example.com"